project_name: nats-streaming-server

release:
  github:
    owner: nats-io
    name: nats-streaming-server
  name_template: 'Release {{.Tag}}'
  draft: true

changelog:
  skip: true

builds:
- main: ./nats-streaming-server.go
  binary: nats-streaming-server
  ldflags:
    - -w -X github.com/nats-io/nats-streaming-server/server.gitCommit={{.ShortCommit}} -X github.com/nats-io/nats-server/v2/server.gitCommit=1712ee3
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  - 386
  goarm:
  - 6
  - 7
  ignore:
    - goos: darwin
      goarch: 386

nfpms:
  - file_name_template: '{{.ProjectName}}-{{.Tag}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
    homepage:  https://nats.io
    description: High-Performance Streaming server for NATS, the cloud native messaging system.
    maintainer: Ivan Kozlovic <ivan@synadia.com>
    license: Apache 2.0
    vendor: Synadia Inc.
    formats:
    - deb
    - rpm

archives:
  - name_template: '{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
    wrap_in_directory: true
    format: zip
    files:
      - README.md
      - LICENSE
  - name_template: '{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
    id: targz-archives
    wrap_in_directory: true
    format: tar.gz
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'SHA256SUMS'
  algorithm: sha256
